[package]
name = "flow-proxy-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
flow-proxy = { path = ".." }

[[bin]]
name = "decoders"
path = "fuzz_targets/decoders.rs"
test = false
doc = false

[[bin]]
name = "frame_reader"
path = "fuzz_targets/frame_reader.rs"
test = false
doc = false
